from .grid_outage import GRID_OUTAGE_SCENARIO
from .extreme_weather import EXTREME_WEATHER_SCENARIO
from .demand_surge import DEMAND_SURGE_SCENARIO

ALL_SCENARIOS = {
    GRID_OUTAGE_SCENARIO["id"]: GRID_OUTAGE_SCENARIO,
    EXTREME_WEATHER_SCENARIO["id"]: EXTREME_WEATHER_SCENARIO,
    DEMAND_SURGE_SCENARIO["id"]: DEMAND_SURGE_SCENARIO,
}
